MACRO(ADD_IDE_FILTERS CurProject)
	set( _src_root_path ${CMAKE_CURRENT_SOURCE_DIR} )
	foreach(_source IN ITEMS ${CurProject})
		get_filename_component(_source_path "${_source}" PATH)
		file(RELATIVE_PATH _source_path_rel "${_src_root_path}" "${_source_path}")
        if( MSVC )
            string(REPLACE "/" "\\" _group_path "${_source_path_rel}")
        else()
            string(REPLACE "/" ";" _group_path_ "${_source_path_rel}")
            list( GET 0 _group_path_ _group_path )
        endif( MSVC )
		source_group("${_group_path}" FILES "${_source}")
    endforeach()
ENDMACRO(ADD_IDE_FILTERS)
