#pragma once

enum class eMaterialType {
    MT_Asphalt = 0,
    MT_Dirt = 1,
    MT_Grass = 2,
    MT_Rock = 3,
    MT_Water = 4,
    MT_Wood = 5,
    MT_Metal = 6,
    MT_Plastic = 7,
    MT_Concrete = 8,
    MT_Pavement = 9,
    MT_Rubber = 10,
    MT_Vegetation1 = 11,
    MT_Vegetation2 = 12,
    MT_Vegetation3 = 13,
    MT_Tires = 14,
    MT_Hood = 15,
    MT_Roof = 16,
    MT_Chassis = 17,
    MT_Body = 18,
    MT_BodyF = 19,
    MT_BodyR = 20,
    MT_BodyFL = 21,
    MT_BodyFR = 22,
    MT_BodyRL = 23,
    MT_BodyRR = 24,
    MT_BodyML = 25,
    MT_BodyMR = 26,
    MT_BumperF = 27,
    MT_BumperR = 28,
    MT_BumperFL = 29,
    MT_BumperFR = 30,
    MT_BumperRL = 31,
    MT_BumperRR = 32,
    MT_DoorF = 33,
    MT_DoorR = 34,
    MT_DoorRL = 35,
    MT_DoorRR = 36,
    MT_DoorFL = 37,
    MT_DoorFR = 38,
    MT_SP1 = 39,
    MT_SP2 = 40,
    MT_SP3 = 41,
    MT_SP4 = 42,
    MT_Foliage1 = 43,
    MT_Foliage2 = 44,
    MT_Foliage3 = 45,
    MT_Foliage4 = 46,
    MT_Default = 47,
    MT_Count = 48
};

